{% set name = "p7zip" %}
{% set version = "16.02" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/p7zip/files/p7zip/{{ version }}/p7zip_{{ version }}_src_all.tar.bz2
  sha256: 5eb20ac0e2944f6cb9c2d51dd6c4518941c185347d4089ea89087ffdd6e2341f
  patches:
    - 12-CVE-2016-9296.patch
    - 13-CVE-2017-17969.patch
    - 14-Fix-g++-warning.patch
    - clang.diff
    # https://salsa.debian.org/debian/p7zip-rar/-/tree/debian/16.02-3/debian/patches
    - 06-CVE-2018-5996.patch
    - CVE-2018-10115.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - patch                  # [not win]
    - m2-patch               # [win]
  host:
  run:

test:
  commands:
    - touch xxx
    - 7z a xxx.7z xxx
    - 7za a xxx.7z xxx
    - 7zr a xxx.7z xxx

about:
  home: https://sourceforge.net/projects/p7zip/
  summary: p7zip is a port of the Windows programs 7z.exe and 7za.exe provided by 7-zip.
  description: |
    7-zip is a file archiver with the highest compression ratio. See
    for more information www.7-zip.org site.
  license: LGPL-2.0-or-later AND LicenseRef-scancode-rar-winrar-eula
  license_family: Other
  license_file: DOC/License.txt
  doc_url: https://sourceforge.net/projects/p7zip/
  dev_url: https://sourceforge.net/projects/p7zip/

extra:
  recipe-maintainers:
    - bgruening
    - isuruf
    - katietz
