travis:
  secure:
    BINSTAR_TOKEN: cqKJ7ivS7tR/cdG2G3OGDW4OEw47frd9UJcdf2tgq+dNLmEMwa+R55UAfGXI4Hiu3sBdebFP0eO+bamNQSkqLDUniWAkgyd+sF7VI4/4usJQW3cjqkE3l57Wz9u6g8p10ZQ2IfzTIa38X2qdIS67Bn0ze8JPpMnZa1wZ9FCjQw7VWmLr9mq0UZUvytCyEhp/2LcymCX51BriCQI4ru0I0LtZBHjb+l+Rc5EvjzCjkd1xeOQ1nXwS8MCtdZ6Cmvad5olH/iHDq56uKnNOG9IjLHCVLxK5hty5aA2/lzI3fmhvB7Zg42+EdsxqIlUdd+rXT4vD6EMf4LfgtQwaL//5NcHeqjVN30/Jw7WxTVStJVNnuOJdLUS0N6FZRvzKUvrJvTLj7E7rB1QXGq3RoqhxIQ2s7jTC6AsS3gV/6wulG1k0rjUnKTu93EDWEQRZM8ymoQZEn09sAFdHRkznzLOTN1nDIvJYHT5YjqqzdTtzZKwx+hVxfpS3t/pQrDq7ftaMsZc5iVAmWaUTdlPVV9FMGayn350RwU1TC5Q66JbUjWqudo/NpCjyVtwIpvVXic7lJD7uN+SCtMGh5x6NEwj0iob1psLNEJgbg4ZejHPqHPfViYpG41XMF0/BRG0LNHklXx8MtlDnGB33wmc4caV6IjDBnwGmWd0YSp0nSFV5f3A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
